version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "WeddingRsvp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1g00rujvefkrn"
s3_prefix = "WeddingRsvp"
region = "us-west-2"
profile = "mwjones"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

